### ISSUE TITLE
Api support

### ISSUE THREAD

**Issue by 0312birdzhang** [julianlam/nodebb-plugin-solr#43]
Hi, i use `nodebb-plugin-write-api`'s token, try to access via api like:
`curl -H "Authorization: Bearer xxxxxx-cb5c-4ddf-866d-5fcbfd2986e8"  'https://example.com/api/search?term=test&in=titlesposts' -v`
But, it return `"not-authorized"`, seem not support access via api

**Comment by Dravere** [comment]
This doesn't sound like a problem of this plugin. Since you're contacting the general NodeBB search API. Authorization and the front-end of the searching isn't done by this plugin. This plugin only has an API for the plugin's settings. You're probably better off to ask in the [NodeBB community](https://community.nodebb.org/) or in the issue tracker of [`nodebb-plugin-write-api`](https://github.com/NodeBB/nodebb-plugin-write-api).

**Comment by julianlam** [comment]
:+1: `/search` is handled in core, so you can also file the bug there. FWIW I think the search endpoint should work with bearer token as well.

However @Dravere is right this is not the right repo for it. Thanks.
