### ISSUE TITLE
admin 504

### ISSUE THREAD

**Issue by bestvist** [julianlam/nodebb-plugin-solr#51]
when i install nodebb-plugin-solr,
then i run ./nodebb build,
result, nodebb admin web page 504
why?

**Comment by Dravere** [comment]
Is there any error in your NodeBB logs? Could you provide that error to us? You can find the log file in the logs folder in your NodeBB installation.

**Comment by bestvist** [comment]
i watch log file no error warning.
i am clean mongodb and run ./nodebb setup is OK.
very strange.

**Comment by Dravere** [comment]
With this little information I can't really help.

The only thing I could think of at the moment, but that is kind of unlikely, is that you have no Solr running or NodeBB is unable to reach the configured Solr instance. And this problem only occurs because your reverse proxy has a too small timeout set. But this is really kind of an unlikely scenario.

I need more information, because I can't reproduce this.

Just to make sure: Which version of `nodebb-plugin-solr` are you using? And which version of Solr?

**Comment by 0312birdzhang** [comment]
I have the same issue, after disable `nodebb-plugin-solr` all is working.
solr:
```
bird@vultr:~$ apt-cache policy  solr-tomcat
solr-tomcat:
  Installed: 3.6.2+dfsg-18~18.04
  Candidate: 3.6.2+dfsg-18~18.04
  Version table:
 *** 3.6.2+dfsg-18~18.04 500
        500 http://archive.ubuntu.com/ubuntu cosmic-updates/universe amd64 Packages
        500 http://archive.ubuntu.com/ubuntu cosmic-updates/universe i386 Packages
        500 http://security.ubuntu.com/ubuntu cosmic-security/universe amd64 Packages
        500 http://security.ubuntu.com/ubuntu cosmic-security/universe i386 Packages
        100 /var/lib/dpkg/status
     3.6.2+dfsg-14 500
        500 http://archive.ubuntu.com/ubuntu cosmic/universe amd64 Packages
        500 http://archive.ubuntu.com/ubuntu cosmic/universe i386 Packages
```
I found uninstall `nodebb-plugin-solr` no clean database "settings:solr" values, manually delete it solved my issue.

**Comment by keramist** [comment]
2020-03-17T17:50:48.057Z [4567/1472] - warn: [plugins] Unable to parse library for: nodebb-plugin-solr
2020-03-17T17:50:48.058Z [4567/1472] - error: TypeError: Class constructor LRUCache cannot be invoked without 'new'
